# MkDocs main configuration file.
# This is an example mkdocs.yml that can form the basic of your own site.
# For its documentation go to: https://www.mkdocs.org
# You will need to change most of the settings here.

site_name: "Data Directory Catalog"
site_url: "http://localhost"
repo_url: https://code.research.uts.edu.au/950654/data_dir_cataloger
use_directory_urls: true

markdown_extensions:
  - tables
  - smarty
  - toc:
      toc_depth: 2
      permalink: True
      separator: "_"

# The macros plugin for MkDocs is very useful. Docs for that are here: 
# https://mkdocs-macros-plugin.readthedocs.io/en/latest/
plugins:
    - search

# Themes supplied with MkDocs are: mkdocs readthedocs.
# To use the material theme: "pip install mkdocs-material".
theme:
  logo: images/uts_logo.png
  name: material
  features:  
    - navigation.instant
    - navigation.top        # Creates a back-to-top "arrow icon" at bottom RHS.
    #- navigation.tabs      # Top-level sections are rendered in a menu layer below the header.
    - navigation.expand     # Left sidebar will expand all collapsible subsections by default.

extra_css: [css/extra.css]

# Example nav settings for our eResearch site.
nav:
  - "Home": index.md
  - "Directories":
    - "/shared": shared.md
    - "/shared/eresearch": shared_eresearch.md
    - "/shared/eresearch/pbs_job_examples": shared_eresearch_pbs_job_examples.md
    - "/shared/opt": shared_opt.md
    - "/shared/c3": shared_c3.md
    - "/shared/isf": shared_isf.md
  - "How does this Work?": how.md
  - "About this Site": about.md

